### ISSUE TITLE
pass parameters to the viewer 

### ISSUE THREAD

**Issue by EyalYasovsky** [heejune/WinForm-PDFjs#1]
Hi,
How can I pass parameters to the viewer?
for example the 'nameddest' param in order to open the pdf on a specific location?

Thanks,
Eyal

**Comment by heejune** [comment]
Hi @EyalYasovsky, 

I think you should figure it out first how it's done from a javascript side regardless of hosted from C# or not.  For example, if you know how to pass a parameter to the PDFViewerApplication object which is accessible from global(window) to set the 'nameddest' variable, then you will also set the parameter and invoke it from C# code naturally.

The 'nameddest' variable you mentioned is the parameter result got from PDFLinkService_setHash. So I guess you probably can set the value by calling the PDFViewerApplication.pdfLinkService.setHash.

**Comment by EyalYasovsky** [comment]
Hi,
I found a very simple solution that fixes the issue.
All I do is add the parameter I want to pass as a part of the html. like this:
var view_page = String.Format("file:///{0}/web/viewer.html?#nameddest={1}", dir, dest);
And now everything works, and the pdf opens on the right destination.
Thanks for your help,
Eyal
